### ISSUE TITLE
Get more than 200 favorite records

### ISSUE THREAD

**Issue by kamontia** [chaspy/favsearch#6]
Refer : #4

Possible to have got favorite records up to 200 already.
But we need to have some plan to get more than 200 favorite records. 

Effective that using `max_id` and `since_id` parameter.

**Comment by chaspy** [comment]
- [ ] get 400 favorites
- [ ] get 1000 favorites

Getting more than favorites, we should concern the cache or API load.

**Comment by chaspy** [comment]
Try `websocket` 💪

**Comment by chaspy** [comment]
Currently, it is not asynchronous, but we can get 1000 favorites 👍 
We will implement that notification to mean "Loading"
https://github.com/chaspy/favsearch/issues/68

close!
